# Generated by Django 4.2.7 on 2025-11-30 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField(db_index=True, verbose_name='Дата бронирования')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Цель бронирования')),
                ('cancellation_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен отмены')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('cancelled', 'Отменено')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменено')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'db_table': 'bookings',
                'ordering': ['-booking_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('capacity', models.IntegerField(default=1, verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('equipment', models.JSONField(blank=True, default=list, verbose_name='Оборудование')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'db_table': 'rooms',
                'ordering': ['name'],
            },
        ),
    ]
